# Nome do seu workflow, aparecerá na aba "Actions" do GitHub
name: Deploy ondg-planos

on:
  # Permite que você rode este workflow manualmente também
  workflow_dispatch:

# Permissões para os jobs
permissions:
  contents: read

jobs:
  # --- JOB PARA PUBLICAR O GUIA ondg-planos 
  deploy:
    name: Deploy ondg-planos to 'ondg-planos' repo
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do código do monorepo
        uses: actions/checkout@v4

      - name: 2. Setup PNPM (ou npm/yarn) e Node.js
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0 # Use a versão do pnpm que desejar
      - uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a versão do Node.js que desejar
          cache: 'pnpm'

      - name: 3. Instalar dependências
        run: pnpm install

      - name: 4. Build do 'ondg-planos'
        run: pnpm turbo build --filter=ondg-planos

      # --- PASSO DE DIAGNÓSTICO ---
      # Adicione este passo para verificar o que foi gerado
      #- name: 4.5. Verificar o conteúdo da pasta de build
      #  run: |
      #    echo "Verificando o que existe na raiz do projeto..."
      #    ls -l
      #    echo "--------------------------------------------------"
      #    echo "Verificando o conteúdo da pasta 'apps/ondg-planos/build'..."
      #    ls -R ./apps/ondg-planos/build

      - name: 5. Deploy para o repositório
        uses: peaceiris/actions-gh-pages@v4
        with:
          # O PAT que você criou e salvou nos secrets
          personal_token: ${{ secrets.PAT_PARA_DEPLOY }}
          # O repositório de destino
          external_repository: Parau/ondg-planos
          # A pasta que contém o resultado do build do 'ondg-planos'
          publish_dir: ./apps/ondg-planos/build
          # A branch no repositório de destino
          publish_branch: gh-pages
          # Informações do usuário que fará o commit (o bot)
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "Deploy ondg-planos: ${{ github.event.head_commit.message }}"
